[[platforms]]
os = "noble"
archs = ["aarch64", "x86_64"]
packages = [
  "libc6-dev",
  "fontconfig-config",
  "fonts-dejavu-core",
  "fonts-dejavu-mono",
  "libaom3",
  "libc-bin",
  "libc-dev-bin",
  "libc-devtools",
  "libc6",
  "libcrypt-dev",
  "libde265-0",
  "libdeflate0",
  "libfontconfig1",
  "libfreetype6",
  "libgd3",
  "libheif-plugin-aomdec",
  "libheif-plugin-aomenc",
  "libheif-plugin-libde265",
  "libheif1",
  "libjbig0",
  "libjpeg-turbo8",
  "libjpeg8",
  "liblerc4",
  "libpng16-16t64",
  "libsharpyuv0",
  "libtiff6",
  "libwebp7",
  "libx11-6",
  "libx11-data",
  "libxau6",
  "libxcb1",
  "libxdmcp6",
  "libxpm4",
  "linux-libc-dev",
  "locales",
  "manpages",
  "manpages-dev",
  "rpcsvc-proto",
  "libatomic1",
  "libedit-dev",
  "libbsd-dev",
  "libgpm2",
  "libmd-dev",
  "libncurses-dev",
  "libncurses6",
  "libssl-dev",
  "libssl3t64",
  "openssl",

  "libgtk-3-dev",
]
deleted_patterns = [
  "*.pc",
  "*/gconv.h",
  "*/libasan*",
  "*/libc.a",
  "*/libedit.a",
  "*/liblsan*",
  "*/libm-*.a",
  "*/libmd.a",
  "*/libpanel.a",
  "*/libstdc*.a",
  "*/libtinfo.a",
  "*/libtsan*",
  "*/libubsan*",
  "etc",
  "usr/bin",
  "usr/lib/ssl",
  "usr/lib/*-linux-gnu/audit",
  "usr/lib/*-linux-gnu/gconv",
  "usr/lib/*-linux-gnu/pkgconfig",
  "usr/lib/valgrind",
  "usr/share",
]
